### ISSUE TITLE
illegal move ClassicAra-0.8.4

### ISSUE THREAD

**Issue by masterkni666** [QueensGambit/CrazyAra#83] opened 2021-04-11 00:49 UTC
```
[Event "?"]
[Site "?"]
[Date "2021.04.10"]
[Round "12"]
[White "ClassicAra_pre_pull47"]
[Black "ClassicAra_084"]
[Result "1-0"]
[ECO "A47"]
[GameDuration "00:00:07"]
[GameEndTime "2021-04-10T17:36:43.795 Pacific Daylight Time"]
[GameStartTime "2021-04-10T17:36:36.352 Pacific Daylight Time"]
[Opening "Queen's Indian defense"]
[PlyCount "111"]
[Termination "illegal move"]
[TimeControl "5+0.01"]

1. d4 {book} Nf6 {book} 2. Nf3 {book} b6 {book} 3. c4 {book} Bb7 {book}
4. g3 {book} Bxf3 {book} 5. exf3 {book} e6 {book} 6. Bg2 {book} d5 {book}
7. O-O {book} Be7 {book} 8. f4 {book} c6 {book} 9. f5 {+1.66/13 0.070s}
exf5 {-1.50/20 0.13s} 10. cxd5 {+1.60/18 0.070s} cxd5 {-1.33/23 0.13s}
11. Qa4+ {+1.56/17 0.073s} Qd7 {-1.51/21 0.13s} 12. Qxd7+ {+1.78/19 0.076s}
Kxd7 {-1.64/19 0.13s} 13. Nc3 {+1.70/16 0.076s} Nc6 {-1.66/20 0.13s}
14. Nxd5 {+1.69/14 0.078s} Rac8 {-1.54/20 0.13s} 15. Rd1 {+1.91/16 0.080s}
Nxd5 {-1.57/19 0.13s} 16. Bxd5 {+1.71/14 0.082s} Bf6 {-1.66/30 0.13s}
17. Be3 {+1.67/16 0.083s} Ke7 {-1.57/22 0.13s} 18. Rac1 {+1.94/13 0.087s}
Nb4 {-1.41/21 0.13s} 19. Bb3 {+1.65/22 0.089s} Rxc1 {-1.23/19 0.13s}
20. Rxc1 {+1.32/18 0.090s} Rd8 {-1.26/16 0.14s} 21. Rc7+ {+1.23/16 0.094s}
Rd7 {-1.05/15 0.14s} 22. Rxd7+ {+1.27/17 0.096s} Kxd7 {-1.37/19 0.14s}
23. Bxf7 {+1.35/19 0.098s} Nc2 {-1.41/16 0.14s} 24. Bg8 {+1.41/17 0.10s}
h6 {-1.29/18 0.14s} 25. Bd2 {+1.63/16 0.10s} Nxd4 {-1.59/16 0.14s}
26. Kg2 {+1.83/14 0.11s} Nc6 {-1.66/15 0.14s} 27. b3 {+1.86/14 0.11s}
Kd6 {-1.71/13 0.14s} 28. Bh7 {+1.95/11 0.12s} Ne7 {-1.77/16 0.15s}
29. h4 {+1.95/14 0.12s} g5 {-1.42/14 0.15s} 30. Kf3 {+1.72/12 0.13s}
Ke5 {-1.20/17 0.15s} 31. hxg5 {+1.37/11 0.046s} hxg5 {-1.09/11 0.071s}
32. Ke2 {+1.35/9 0.043s} Ke6 {-1.21/15 0.068s} 33. Kd3 {+1.15/11 0.041s}
b5 {-1.03/13 0.065s} 34. f3 {+1.39/10 0.039s} Nc6 {-0.83/9 0.061s}
35. Bg8+ {+0.79/8 0.039s} Kd6 {-0.75/7 0.059s} 36. Bh7 {+0.90/6 0.037s}
Ke6 {-0.82/5 0.056s} 37. Ke2 {+1.19/10 0.036s} Nd4+ {-1.26/11 0.054s}
38. Kf2 {+1.29/14 0.034s} Nc6 {-0.93/16 0.052s} 39. Bg8+ {+0.90/10 0.032s}
Kd6 {-0.87/7 0.050s} 40. Bf7 {+1.03/8 0.031s} a5 {-0.91/12 0.049s}
41. Bg6 {+1.68/11 0.030s} Ne7 {-0.93/15 0.046s} 42. Bh7 {+1.26/10 0.029s}
a4 {-1.12/13 0.044s} 43. bxa4 {+1.22/11 0.029s} bxa4 {-1.48/14 0.042s}
44. Ke2 {+1.89/12 0.028s} Kc5 {-1.17/14 0.041s} 45. Kd3 {+1.45/10 0.026s}
Kb5 {-0.83/11 0.040s} 46. g4 {+1.24/9 0.026s} f4 {-0.56/13 0.039s}
47. Be4 {+0.91/10 0.025s} Kc5 {-0.68/12 0.036s} 48. Ba5 {+0.74/10 0.024s}
Nd5 {-0.31/16 0.035s} 49. Bxd5 {+0.86/12 0.023s} Kxd5 {-1.05/10 0.033s}
50. Bb4 {+1.29/9 0.023s} Bd8 {-0.91/8 0.032s} 51. Bf8 {+1.13/7 0.022s}
Bf6 {-0.81/6 0.031s} 52. Bb4 {+0.60/5 0.023s} Bd8 {-0.50/4 0.030s}
53. Bf8 {+0.40/3 0.021s} Bf6 {-0.38/2 0.030s} 54. Ba3 {+0.81/14 0.020s}
Bd8 {-0.50/11 0.028s} 55. Bb4 {+0.87/13 0.020s} Bf6 {-0.64/13 0.027s}
56. Bf8 {+0.79/14 0.019s, Black makes an illegal move: d8f6} 1-0
```

**Comment by QueensGambit** [comment] 2021-04-11 12:22
I think this problem is because a cycle occurred within the graph.
This usually happened in chess endgames when a position has been repeated.

The cause of this issue is that the number of plies were previously checked using

https://github.com/QueensGambit/CrazyAra/blob/500da21e0bd9152657adbbc6118f3ebbc660e449/engine/src/chess_related/board.cpp#L114

instead of

https://github.com/QueensGambit/CrazyAra/blob/500da21e0bd9152657adbbc6118f3ebbc660e449/engine/src/chess_related/boardstate.cpp#L77

For [release 0.9.0](https://github.com/QueensGambit/CrazyAra/releases/tag/0.9.0), this should be fixed and no cycles should occur.

**Comment by QueensGambit** [comment] 2021-04-11 12:34
Disabling the UCI option `Reuse_Tree` for both binaries should solve this problem also.
However, when `Reuse_Tree` is deactivated a lot less simulations are used and the results are a slightly distorted.

**Closed** 2021-04-11 12:52 UTC
Labels: bug, chess
